{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-sequin
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-sequin
                port:
                  number: {{ .Values.sequin.service.port }}
  {{- with .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ $.Values.ingress.host }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}